
INSERT INTO clubs (nom, description) VALUES ('AppsClub', 'Club dédié au développement d''applications mobiles et web. Il organise des ateliers de codage (iOS, Android, web), des hackathons, et des projets de groupe pour créer des applications utiles pour l''établissement ou pour participer à des concours.');
INSERT INTO clubs (nom, description) VALUES ('ClubMecanique', 'Regroupe les passionnés de génie mécanique. Les membres travaillent sur des projets concrets comme la restauration de véhicules, la conception de prototypes (ex: drones, robots), ou la participation à des compétitions d''ingénierie.');
INSERT INTO clubs (nom, description) VALUES ('ClubSocial', 'Club dont la mission est d''animer la vie de l''établissement et de renforcer les liens. Il organise des événements de rencontre, des activités d''intégration pour les nouveaux, et des actions de bénévolat et de solidarité.');
INSERT INTO clubs (nom, description) VALUES ('ClubSportif', 'Gère et promeut les activités sportives au sein de l''établissement. Il organise les entraînements, les tournois inter-classes (foot, basket, volley...), et gère l''accès aux équipements sportifs.');
INSERT INTO clubs (nom, description) VALUES ('ClubElectrique', 'Club centré sur l''électronique et le génie électrique. Il propose des ateliers de soudure, de programmation de microcontrôleurs (Arduino, Raspberry Pi), et la réalisation de projets (ex: domotique, systèmes embarqués).');
INSERT INTO clubs (nom, description) VALUES ('ClubIndustriel', 'Pont entre les étudiants et le monde de l''industrie. Ce club organise des visites d''usines, des conférences avec des professionnels, et des formations certifiantes (ex: Lean Six Sigma, gestion de la chaîne logistique).');
INSERT INTO clubs (nom, description) VALUES ('ClubAstronomique', 'Regroupe les passionnés d''astronomie. Le club organise des soirées d''observation avec télescopes, des conférences sur l''astrophysique, et des ateliers pour apprendre à se repérer dans le ciel.');
INSERT INTO clubs (nom, description) VALUES ('ClubEcolos', 'Le club vert de l''établissement. Il mène des actions de sensibilisation à l''écologie, organise des campagnes de recyclage, des opérations de nettoyage ("clean-up days"), et promeut le développement durable sur le campus.');
INSERT INTO clubs (nom, description) VALUES ('ClubCreart', 'Dédié à l''expression artistique. Il regroupe les talents en dessin, peinture, photographie, et design. Il organise des expositions, des ateliers créatifs, et décore les espaces de l''établissement.');
INSERT INTO clubs (nom, description) VALUES ('BlockChainClub', 'Club visant à démystifier les technologies de la blockchain. Il explore les cryptomonnaies, les NFT, et le développement d''applications décentralisées (dApps) à travers des conférences et des ateliers pratiques.');
INSERT INTO clubs (nom, description) VALUES ('ClubFSF', 'Club dédié à la promotion des logiciels libres et de la culture "open-source". Il organise des "install-party" Linux, des ateliers sur les outils libres (GIMP, Blender, LibreOffice), et des débats sur la liberté numérique.');
INSERT INTO clubs (nom, description) VALUES ('ClubCivil', 'Destiné aux étudiants en génie civil. Il organise des visites de chantiers, des conférences sur les nouvelles techniques de construction, et des ateliers sur des logiciels de modélisation (ex: AutoCAD, BIM).');
INSERT INTO clubs (nom, description) VALUES ('TradersClub', 'Club d''initiation aux marchés financiers. Il organise des simulations de trading, des conférences sur l''économie et la finance, et des ateliers d''analyse technique pour apprendre à investir.');
